sudo: required

language: java

matrix:
  include:
    - jdk: oraclejdk10
        addons:
          apt:
            packages:
              - oracle-java10-installer # https://docs.travis-ci.com/user/languages/java/#Updating-Oracle-JDK-to-a-recent-release

script:
- "./gradlew test"

before_install:
- chmod a+x gradlew
